#application under test
browser=chrome
headless=false
base_url = https://the-internet.herokuapp.com

# Page paths
login_url_path=/login
secure_url_path=/secure
dropdown_url_path=/dropdown

# Wait timeout in seconds
default_timeout=10

# Test credentials
valid_username=tomsmith
valid_password=SuperSecretPassword!
invalid_username=wrong_user
invalid_password=wrong_password